import type { PublicLandingLocale } from "./publicLandingLocale";

type Section = { heading: string; paragraphs?: string[]; points?: string[] };
type DocumentCopy = { title: string; intro: string; sections: Section[] };

export const LEGAL_COPY: Record<PublicLandingLocale, { shell: {
  label: string; language: string; signIn: string; home: string; privacy: string; terms: string;
  updated: string; contact: string; privacyLink: string;
}; privacy: DocumentCopy; terms: DocumentCopy }> = {
  ru: {
    shell: { label: "Информация для учеников", language: "Язык страницы", signIn: "Войти", home: "Главная", privacy: "Конфиденциальность", terms: "Условия обучения", updated: "Обновлено: 29 сентября 2026 г.", contact: "Вопросы об условиях, данных или записи уроков:", privacyLink: "Политика конфиденциальности" },
    privacy: { title: "Политика конфиденциальности", intro: "Какие данные нужны для обучения, расписания и записи уроков и как обратиться к нам по вопросам данных.", sections: [
      { heading: "1. Какие данные мы собираем", points: [
        "Аккаунт и связь: имя, электронная почта, телефон; для несовершеннолетнего — имя и контакт родителя или законного представителя.",
        "Настройки обучения: часовой пояс, формат времени, родной язык, возраст, уровень английского, цели, интересы и предпочтения по расписанию.",
        "Учебная деятельность: записи и транскрипты уроков, заметки, словарь, карточки, домашние задания, ответы, обратная связь, посещаемость и прогресс.",
        "Расписание и операции: бронирования, переносы, отмены, остаток уроков, пакеты, учебные и финансовые записи.",
        "Источник регистрации: метки UTM и ref из ссылки и ответ о том, откуда вы узнали об академии."
      ] },
      { heading: "2. Как мы используем данные", paragraphs: ["Данные помогают создать аккаунт, подобрать и провести урок, показать время в вашем часовом поясе, связать вас с преподавателем, вести расписание и остаток уроков, подготовить учебные материалы, отслеживать прогресс, отвечать на обращения и оценивать эффективность рекламы."] },
      { heading: "3. Запись, транскрипция и ИИ", paragraphs: ["Онлайн-уроки записываются и транскрибируются. Запись и текст используются для конспектов, словаря, карточек, заданий и тестов, а также для проверки спорных ситуаций. Преподаватель проверяет материалы перед публикацией. Для транскрибации и подготовки материалов используются внешние технические сервисы; им передаются данные, необходимые для соответствующей функции.", "Согласие на запись и обработку учебного содержания запрашивается при оформлении обучения и сохраняется с датой. Если вы хотите отозвать согласие для будущих уроков, свяжитесь с нами: запись и обработка являются частью обучения, поэтому мы обсудим возможность его продолжения. Отзыв не отменяет обработку, выполненную ранее."] },
      { heading: "4. Несовершеннолетние", paragraphs: ["Для ученика младше 18 лет запрашиваются имя и телефон родителя или законного представителя. Представитель должен согласиться с обучением, записью и обработкой данных ребёнка. Не регистрируйте несовершеннолетнего без такого согласия."] },
      { heading: "5. Срок хранения", paragraphs: ["По действующей политике академии записи уроков и транскрипты хранятся бессрочно; хранилищем управляют вручную. Учебные, аккаунтные, финансовые и операционные записи хранятся столько, сколько необходимо для предоставления услуг, истории обучения, разрешения споров и выполнения обязательных требований. Политика хранения может быть пересмотрена."] },
      { heading: "6. Доступ и защита", paragraphs: ["Доступ зависит от роли и необходимости: ученик видит свои данные, преподаватель — данные назначенных ему учеников, администрация — данные для работы академии. Мы разграничиваем доступ и не продаём персональные данные."] },
      { heading: "7. Ваши запросы", paragraphs: ["Вы можете попросить исправить неточные данные, узнать, как используются ваши данные, или обсудить удаление. Некоторые сведения нельзя удалить немедленно, если они нужны для истории оказанной услуги, финансового учёта, безопасности или разрешения спора. Мы объясним применимое ограничение в ответе."] }
    ] },
    terms: { title: "Условия обучения", intro: "Условия индивидуальных онлайн-уроков, пакетов, расписания, материалов и записи занятий Omnica English.", sections: [
      { heading: "1. Формат обучения", paragraphs: ["Omnica English проводит индивидуальные онлайн-уроки английского через Google Meet, обычно по 60 минут. Кабинет используется для расписания, учебных материалов, домашней работы, словаря, прогресса и остатка уроков."] },
      { heading: "2. Аккаунт и данные", paragraphs: ["Вы отвечаете за доступ к аккаунту и точность имени, контактов, часового пояса и учебной информации. Не передавайте доступ другому человеку. Время уроков показывается в часовом поясе вашего профиля."] },
      { heading: "3. Запись и согласие", paragraphs: ["Уроки записываются, транскрибируются и обрабатываются для подготовки конспектов, словаря, карточек, заданий и тестов. Согласие требуется при оформлении обучения. Для ученика младше 18 лет требуется согласие и контакт родителя или законного представителя."] },
      { heading: "4. Пакеты и пробные уроки", paragraphs: ["Для каждого предлагаемого пакета каталог показывает программу, название, цену и валюту, количество уроков, срок действия и все преимущества. Указанные условия могут меняться; перед запросом ориентируйтесь на актуальный каталог. Один учебный кредит отображается как один урок. Запрос пакета не начисляет уроки автоматически: предоставление после проверки оплаты выполняет администрация.", "Срок стандартного пакета начинается с первого фактического использования. Уже забронированный оплаченный урок остаётся оплаченным, даже если неиспользованный остаток позднее истечёт. Пробный урок, если предложение включено академией, не является подпиской, скидкой или купленным пакетом."] },
      { heading: "5. Бронирование, перенос и отмена", paragraphs: ["Доступное время и ограничения указаны в календаре. Самостоятельное бронирование требует заблаговременного выбора времени и зависит от доступности, остатка уроков, дневных и недельных лимитов. Перед подтверждением отмены или переноса показывается последствие для урока и баланса. Своевременные отмены могут вернуть урок в пределах лимита бесплатных отмен; поздняя отмена или перенос могут списать урок. Проверяйте показанное последствие до подтверждения."] },
      { heading: "6. Поведение участников", paragraphs: ["Ученик и преподаватель должны уважительно общаться, приходить вовремя и использовать материалы для личного обучения. Нельзя преследовать другого участника, передавать его контакты, запись или транскрипт третьим лицам, нарушать работу сервиса или пытаться получить доступ к чужому аккаунту."] },
      { heading: "7. Материалы и домашняя работа", paragraphs: ["После урока материалы могут готовиться с помощью автоматизированных инструментов; преподаватель проверяет их перед публикацией. Домашняя работа помогает обучению; её выполнение отслеживается, но не служит основанием для автоматического наказания ученика."] },
      { heading: "8. Данные и хранение", paragraphs: ["Обработка данных описана в {privacy}. По действующей политике академии записи уроков и транскрипты хранятся бессрочно и управляются вручную."] },
      { heading: "9. Изменения и споры", paragraphs: ["Условия могут обновляться при изменении продукта или обязательных требований. В случае спора сначала свяжитесь с администрацией. Расписание, записи операций, аудио и транскрипты могут использоваться для проверки фактов. Решения о возвратах или исключительных корректировках принимает администрация и фиксирует их в обычном порядке."] }
    ] }
  },
  kk: {
    shell: { label: "Оқушыларға арналған ақпарат", language: "Бет тілі", signIn: "Кіру", home: "Басты бет", privacy: "Құпиялық", terms: "Оқу шарттары", updated: "Жаңартылған күні: 2026 жылғы 29 қыркүйек", contact: "Шарттар, деректер немесе сабақ жазбалары туралы сұрақтар:", privacyLink: "Құпиялық саясаты" },
    privacy: { title: "Құпиялық саясаты", intro: "Оқу, кесте және сабақ жазбалары үшін қандай деректер қажет және олар туралы бізге қалай хабарласуға болады.", sections: [
      { heading: "1. Қандай деректерді жинаймыз", points: [
        "Аккаунт және байланыс: аты-жөніңіз, электрондық поштаңыз, телефон нөміріңіз; кәмелетке толмаған оқушы үшін ата-анасының немесе заңды өкілінің аты-жөні мен байланыс деректері.",
        "Оқу параметрлері: уақыт белдеуі, уақыт пішімі, ана тілі, жас, ағылшын тілі деңгейі, мақсаттар, қызығушылықтар және кестеге қатысты қалаулар.",
        "Оқу барысы: сабақтың аудиожазбалары мен транскрипттері, жазбалар, сөздік, карточкалар, үй тапсырмалары, жауаптар, кері байланыс, сабаққа қатысу және ілгерілеу.",
        "Кесте мен операциялар: брондау, уақыт ауыстыру, бас тарту, қалған сабақтар, пакеттер, оқу және қаржылық жазбалар.",
        "Тіркелу көзі: сілтемедегі UTM және ref белгілері және академия туралы қайдан білгеніңіз жөніндегі жауабыңыз."
      ] },
      { heading: "2. Деректерді қалай пайдаланамыз", paragraphs: ["Деректер аккаунт ашуға, сабақты таңдап өткізуге, уақытты сіздің уақыт белдеуіңізде көрсетуге, оқытушымен байланыстыруға, кесте мен сабақ қалдығын жүргізуге, оқу материалдарын дайындауға, ілгерілеуді бақылауға, өтініштерге жауап беруге және жарнаманың тиімділігін бағалауға қажет."] },
      { heading: "3. Жазба, транскрипция және ЖИ", paragraphs: ["Онлайн сабақтар жазылып, мәтінге айналдырылады. Жазба мен мәтін конспект, сөздік, карточка, тапсырма және тест дайындауға, сондай-ақ даулы жағдайларды тексеруге пайдаланылады. Жарияламас бұрын материалдарды оқытушы тексереді. Транскрипция мен материал дайындауға сыртқы техникалық қызметтер қатысады; оларға тиісті функцияға қажетті деректер беріледі.", "Оқу мазмұнын жазуға және өңдеуге келісім оқу рәсімделген кезде сұралады және күнімен бірге сақталады. Болашақ сабақтарға келісімді қайтарғыңыз келсе, бізге хабарласыңыз: жазу мен өңдеу оқу үдерісінің бөлігі болғандықтан, оқуды жалғастыру мүмкіндігін бірге талқылаймыз. Келісімді қайтару бұрын жасалған өңдеуді жоққа шығармайды."] },
      { heading: "4. Кәмелетке толмағандар", paragraphs: ["18 жасқа толмаған оқушы үшін ата-анасының немесе заңды өкілінің аты-жөні мен телефоны сұралады. Өкіл баланың оқуына, жазбаға және деректерінің өңделуіне келісуі керек. Мұндай келісімсіз кәмелетке толмаған адамды тіркемеңіз."] },
      { heading: "5. Сақтау мерзімі", paragraphs: ["Академияның қолданыстағы саясаты бойынша сабақ жазбалары мен транскрипттері мерзімсіз сақталады; сақтау қолмен басқарылады. Оқу, аккаунт, қаржылық және операциялық жазбалар қызмет көрсету, оқу тарихы, дауларды шешу және міндетті талаптарды орындау үшін қажетті уақыт бойы сақталады. Сақтау саясаты кейін қайта қаралуы мүмкін."] },
      { heading: "6. Қолжетімділік пен қорғау", paragraphs: ["Қолжетімділік рөл мен қажеттілікке байланысты: оқушы өз деректерін, оқытушы өзіне бекітілген оқушылардың деректерін, әкімшілік академия жұмысына қажет деректерді көреді. Біз қолжетімділікті шектейміз және жеке деректерді сатпаймыз."] },
      { heading: "7. Сұрауларыңыз", paragraphs: ["Сіз қате деректерді түзетуді, олардың қалай пайдаланылатынын түсіндіруді немесе жою мәселесін талқылауды сұрай аласыз. Көрсетілген қызмет тарихы, қаржылық есеп, қауіпсіздік не дауды шешу үшін кейбір деректерді бірден жою мүмкін болмауы мүмкін. Шектеудің себебін жауапта түсіндіреміз."] }
    ] },
    terms: { title: "Оқу шарттары", intro: "Omnica English жеке онлайн сабақтарының, пакеттерінің, кестесінің, материалдарының және жазбаларының шарттары.", sections: [
      { heading: "1. Оқу форматы", paragraphs: ["Omnica English Google Meet арқылы, әдетте 60 минуттық жеке ағылшын сабақтарын өткізеді. Жеке кабинет кестеге, оқу материалдарына, үй тапсырмасына, сөздікке, ілгерілеуге және қалған сабақтарға арналған."] },
      { heading: "2. Аккаунт және деректер", paragraphs: ["Аккаунтыңызға қолжетімділік пен атыңыздың, байланыс деректеріңіздің, уақыт белдеуіңіздің және оқу ақпаратыңыздың дұрыстығына өзіңіз жауап бересіз. Аккаунтты басқа адамға бермеңіз. Сабақ уақыты профиліңіздегі уақыт белдеуінде көрсетіледі."] },
      { heading: "3. Жазба және келісім", paragraphs: ["Конспект, сөздік, карточка, тапсырма және тест дайындау үшін сабақтар жазылады, мәтінге айналдырылады және өңделеді. Оқуды рәсімдеу кезінде келісім қажет. 18 жасқа толмаған оқушы үшін ата-анасының немесе заңды өкілінің келісімі мен байланыс деректері қажет."] },
      { heading: "4. Пакеттер мен сынақ сабақтары", paragraphs: ["Әр ұсынылатын пакет үшін каталогта бағдарлама, атауы, бағасы мен валютасы, сабақ саны, жарамдылық мерзімі және барлық артықшылықтары көрсетіледі. Шарттар өзгеруі мүмкін; сұрау жіберер алдында ағымдағы каталогты тексеріңіз. Бір оқу бірлігі кабинетте бір сабақ ретінде көрсетіледі. Пакетке сұрау жіберу сабақтарды автоматты түрде қоспайды: төлем тексерілгеннен кейін оларды әкімшілік береді.", "Стандартты пакеттің мерзімі алғаш рет нақты пайдаланылған сәттен басталады. Пайдаланылмаған сабақ қалдығының мерзімі кейін бітсе де, алдын ала брондалған ақылы сабақ төленген күйінде қалады. Академия сынақ сабағын ұсынса, ол жазылым, жеңілдік немесе сатып алынған пакет емес."] },
      { heading: "5. Брондау, ауыстыру және бас тарту", paragraphs: ["Бос уақыт пен шектеулер күнтізбеде көрсетіледі. Өз бетіңізше брондау алдын ала уақыт таңдауды талап етеді және бос орынға, сабақ қалдығына, күндік және апталық шектеулерге байланысты. Бас тартуды не уақытты ауыстыруды растау алдында сабақ пен қалдыққа әсері көрсетіледі. Уақтылы бас тарту тегін бас тарту шегі аясында сабақты қайтаруы мүмкін; кеш бас тарту не ауыстыру сабақтың есептен шығарылуына әкелуі мүмкін. Растамас бұрын көрсетілген салдарды тексеріңіз."] },
      { heading: "6. Қатысушылардың мінез-құлқы", paragraphs: ["Оқушы мен оқытушы бір-бірін құрметтеуі, уақытында келуі және материалдарды тек жеке оқу үшін пайдалануы керек. Басқа қатысушыны қудалауға, оның байланыс деректерін, жазбасын немесе транскриптін үшінші тұлғаларға беруге, қызмет жұмысына кедергі келтіруге немесе бөтен аккаунтқа кіруге тырысуға болмайды."] },
      { heading: "7. Материалдар мен үй тапсырмасы", paragraphs: ["Сабақтан кейінгі материалдар автоматтандырылған құралдар көмегімен дайындалуы мүмкін; жарияламас бұрын оларды оқытушы тексереді. Үй тапсырмасы оқуға көмектеседі; оның орындалуы бақыланады, бірақ оқушыны автоматты жазалауға негіз болмайды."] },
      { heading: "8. Деректер және сақтау", paragraphs: ["Деректерді өңдеу {privacy} құжатында сипатталған. Академияның қолданыстағы саясаты бойынша сабақ жазбалары мен транскрипттері мерзімсіз сақталады және қолмен басқарылады."] },
      { heading: "9. Өзгерістер мен даулар", paragraphs: ["Өнім не міндетті талаптар өзгерсе, шарттар жаңартылуы мүмкін. Дау туындаса, алдымен әкімшілікке хабарласыңыз. Мән-жайды тексеру үшін кесте, операция жазбалары, аудио және транскрипттер пайдаланылуы мүмкін. Қаражат қайтару немесе ерекше түзету жөніндегі шешімді әкімшілік қабылдап, әдеттегі тәртіппен тіркейді."] }
    ] }
  },
  en: {
    shell: { label: "Information for students", language: "Page language", signIn: "Sign in", home: "Home", privacy: "Privacy", terms: "Terms of learning", updated: "Updated: 29 September 2026", contact: "Questions about these terms, data or lesson recordings:", privacyLink: "Privacy policy" },
    privacy: { title: "Privacy policy", intro: "What data we need for learning, scheduling and lesson recordings, and how to contact us about your data.", sections: [
      { heading: "1. Data we collect", points: [
        "Account and contact: name, email and phone; for a minor, the name and contact information of a parent or legal guardian.",
        "Learning preferences: time zone, time format, native language, age, English level, goals, interests and preferred schedule.",
        "Learning activity: lesson recordings and transcripts, notes, vocabulary, flashcards, homework, answers, feedback, attendance and progress.",
        "Scheduling and operations: bookings, moves, cancellations, remaining lessons, packs, learning and financial records.",
        "Registration source: UTM and ref parameters from links and your answer about how you heard about the academy."
      ] },
      { heading: "2. How we use data", paragraphs: ["We use data to create an account, arrange and deliver lessons, show times in your time zone, connect you with a teacher, manage your schedule and lesson balance, prepare learning materials, track progress, respond to inquiries and assess advertising performance."] },
      { heading: "3. Recordings, transcription and AI", paragraphs: ["Online lessons are recorded and transcribed. Recordings and transcripts are used for notes, vocabulary, flashcards, assignments and quizzes, and to review disputes. Teachers review materials before publication. External technical services help with transcription and material preparation; they receive the data necessary for those functions.", "Consent to recording and processing of learning content is requested during onboarding and stored with a date. If you wish to withdraw consent for future lessons, contact us first: recording and processing are part of the service, so we will discuss whether learning can continue. Withdrawal does not undo processing already carried out."] },
      { heading: "4. Minors", paragraphs: ["For students under 18, we request a parent or legal guardian’s name and phone number. The guardian must agree to the child’s learning, recording and data processing. Do not register a minor without that consent."] },
      { heading: "5. Retention", paragraphs: ["Under the academy’s current policy, lesson recordings and transcripts are retained indefinitely and managed manually. Learning, account, financial and operational records are kept as needed to deliver the service, preserve learning history, resolve disputes and meet applicable obligations. The retention policy may be reviewed later."] },
      { heading: "6. Access and protection", paragraphs: ["Access depends on role and need: students see their own data, teachers see data for assigned students, and administrators see data needed to run the academy. We restrict access and do not sell personal data."] },
      { heading: "7. Your requests", paragraphs: ["You can ask us to correct inaccurate data, explain how data is used or discuss deletion. Some information cannot be removed immediately when it is needed for the history of services delivered, financial records, security or dispute resolution. We will explain any applicable restriction in our response."] }
    ] },
    terms: { title: "Terms of learning", intro: "Terms for Omnica English one-to-one online lessons, packs, scheduling, materials and recordings.", sections: [
      { heading: "1. Lesson format", paragraphs: ["Omnica English provides one-to-one English lessons online through Google Meet, normally lasting 60 minutes. Your account provides scheduling, learning materials, homework, vocabulary, progress and your remaining lesson balance."] },
      { heading: "2. Account and information", paragraphs: ["You are responsible for access to your account and the accuracy of your name, contact details, time zone and learning information. Do not share account access. Lesson times appear in your profile’s time zone."] },
      { heading: "3. Recording and consent", paragraphs: ["Lessons are recorded, transcribed and processed to prepare notes, vocabulary, flashcards, assignments and quizzes. Consent is required during onboarding. For a student under 18, a parent or legal guardian’s consent and contact details are required."] },
      { heading: "4. Packs and trial lessons", paragraphs: ["For each offered pack, the catalogue shows the programme family, name, price and currency, number of lessons, validity and all benefits. Terms can change; check the current catalogue before requesting a pack. One learning credit is displayed as one lesson. Requesting a pack does not automatically grant lessons: an administrator grants them after payment verification.", "A standard pack’s validity starts on its first actual use. An already booked paid lesson stays paid even if the unused balance expires later. A trial lesson, if the academy enables the offer, is not a subscription, discount or purchased pack."] },
      { heading: "5. Booking, moving and cancelling", paragraphs: ["Available times and limits are shown in the calendar. Self-booking requires advance notice and depends on availability, your lesson balance, and daily and weekly limits. Before you confirm a cancellation or move, the effect on the lesson and your balance is shown. Timely cancellation may return a lesson within the free-cancellation allowance; a late cancellation or move may consume a lesson. Review the displayed consequence before confirming."] },
      { heading: "6. Participant conduct", paragraphs: ["Students and teachers should communicate respectfully, arrive on time and use materials for personal learning only. Do not harass another participant, share their contact details, recording or transcript with third parties, disrupt the service or try to access someone else’s account."] },
      { heading: "7. Materials and homework", paragraphs: ["Post-lesson materials may be prepared with automated tools; teachers review them before publication. Homework supports learning and its completion is tracked, but it does not trigger automatic punishment for a student."] },
      { heading: "8. Data and retention", paragraphs: ["Data processing is described in the {privacy}. Under the academy’s current policy, lesson recordings and transcripts are retained indefinitely and managed manually."] },
      { heading: "9. Changes and disputes", paragraphs: ["These terms may be updated when the product or applicable requirements change. Contact the academy administration first if a dispute arises. The schedule, operation records, audio and transcripts may be used to establish facts. Administrators decide and record any refund or exceptional adjustment through the normal process."] }
    ] }
  }
};
