import type { PublicLandingLocale } from "./publicLandingLocale";

export const PUBLIC_LANGUAGE_OPTIONS = [
  { value: "ru", label: "Русский" },
  { value: "kk", label: "Қазақша" },
  { value: "en", label: "English" },
] as const;

export const LANDING_COPY = {
  ru: {
    language: "Язык страницы", home: "Главная Omnica English", signIn: "Войти", register: "Начать обучение",
    eyebrow: "Английский, который остаётся с вами", heroA: "Говорите на уроке.", heroB: "Помните после него.",
    hero: "Индивидуальные онлайн-занятия с преподавателями из разных стран, в том числе с носителями языка. Живой разговор превращается в слова, карточки и задания для практики между уроками.",
    start: "Начать обучение", explore: "Как это работает", whatsapp: "Написать Omnica English в WhatsApp",
    note: "Уроки один на один · 60 минут · Google Meet", illustration: "Иллюстрация учебного процесса, не снимок кабинета",
    lesson: "На занятии", live: "Транскрипция для преподавателя", review: "После занятия", teacher: "Преподаватель проверяет материалы перед публикацией", word: "Новые слова", wordExample: "Понимать и применять", card: "Карточка для повторения", cardFront: "to make progress", cardBack: "добиваться успеха",
    pillarsEyebrow: "Не только разговор", pillarsTitle: "Урок заканчивается. Обучение продолжается.", pillarsIntro: "Не нужно полагаться только на память: всё нужное для повторения собрано в вашем кабинете.",
    features: [
      ["01 / Живой урок", "Ваш преподаватель ведёт индивидуальный урок в Google Meet. Транскрипция в реальном времени помогает ему работать с материалом занятия."],
      ["02 / Слова в карточки", "После урока преподаватель проверяет конспект и слова, подготовленные с помощью ИИ. Опубликованные слова становятся карточками для повторения."],
      ["03 / Чтение и практика", "Читайте материалы библиотеки, добавляйте слова в свой список и повторяйте их карточками в удобном темпе."],
      ["04 / Домашняя работа", "Выполняйте задания между встречами. Преподаватель проверяет ответы и даёт обратную связь."],
    ],
    readingLabel: "В библиотеке", readingTitle: "Читайте. Замечайте. Запоминайте.", readingText: "Подбирайте тексты по уровню, нажимайте на незнакомое слово и сохраняйте его в свой словарь. Оно попадёт в те же карточки, что и слова из урока.",
    readingSample: "Небольшая история на английском", readingLine: "Every small step helps you grow.", readingHint: "Нажмите на слово в кабинете, чтобы узнать значение и добавить его в словарь.",
    teacherEyebrow: "Люди важнее инструментов", teacherTitle: "Ваш путь — с живым преподавателем.", teacherText: "Индивидуальные занятия ведут преподаватели из разных стран, включая носителей английского. Они подстраивают разговор под вашу цель, проверяют материалы после урока и помогают двигаться дальше. Технологии помогают им, а не заменяют их.",
    processEyebrow: "Простой старт", processTitle: "От первой встречи до привычки говорить", process: ["Создайте аккаунт и расскажите о своей цели.", "Выберите удобное время в своём часовом поясе.", "Общайтесь на уроке и повторяйте слова, чтение и задания после него."],
    pricesEyebrow: "Пакеты", pricesTitle: "Прозрачные условия, ваш темп.", pricesText: "Цены, количество уроков, срок действия и состав каждого пакета берутся из актуального каталога академии.", loading: "Загружаем пакеты", empty: "Пакеты пока не отображаются. Напишите нам, и мы поможем выбрать занятия.", choose: "Начать обучение", packName: "Программа", sale: "Цена со скидкой", trialBody: (n: number) => `После регистрации и заполнения анкеты вам будет доступно ${n === 1 ? "пробное занятие" : `${n} пробных занятий`}, если предложение включено академией.`,
    finalTitle: "Готовы заговорить увереннее?", finalText: "Начните с регистрации. Если есть вопрос об уровне, преподавателях или расписании — напишите нам напрямую.",
    legal: "Юридическая информация", privacy: "Конфиденциальность", terms: "Условия обучения", back: "Наверх", email: "Электронная почта",
  },
  kk: {
    language: "Бет тілі", home: "Omnica English басты беті", signIn: "Кіру", register: "Оқуды бастау",
    eyebrow: "Сабақтан кейін де жалғасатын ағылшын тілі", heroA: "Сабақта сөйлеңіз.", heroB: "Кейін де есте сақтаңыз.",
    hero: "Әртүрлі елдерден келген, оның ішінде ағылшын тілін ана тілі ретінде сөйлейтін оқытушылармен жеке онлайн сабақтар. Сабақтағы әңгіме кейін қайталауға арналған сөздерге, карточкаларға және тапсырмаларға айналады.",
    start: "Оқуды бастау", explore: "Оқу қалай өтеді", whatsapp: "Omnica English-ке WhatsApp арқылы жазу",
    note: "Жеке сабақ · 60 минут · Google Meet", illustration: "Оқу үдерісінің иллюстрациясы, кабинет скриншоты емес",
    lesson: "Сабақта", live: "Оқытушыға арналған тікелей транскрипция", review: "Сабақтан кейін", teacher: "Материал жарияланар алдында оқытушы тексереді", word: "Жаңа сөздер", wordExample: "Түсіну және қолдану", card: "Қайталау карточкасы", cardFront: "to make progress", cardBack: "алға жылжу",
    pillarsEyebrow: "Әңгімемен шектелмейді", pillarsTitle: "Сабақ аяқталады. Оқу жалғасады.", pillarsIntro: "Тек есте сақтауға сүйенбеңіз: қайталауға қажет материалдар жеке кабинетіңізде жиналады.",
    features: [
      ["01 / Тікелей сабақ", "Оқытушыңыз Google Meet арқылы жеке сабақ өткізеді. Нақты уақыттағы транскрипция оған сабақ материалымен жұмыс істеуге көмектеседі."],
      ["02 / Сөздерден карточкалар", "Сабақтан кейін оқытушы ЖИ көмегімен дайындалған конспект пен сөздерді тексереді. Жарияланған сөздер қайталау карточкаларына айналады."],
      ["03 / Оқу және жаттығу", "Кітапхана материалдарын оқып, сөздерді өз тізіміңізге қосыңыз және карточкалармен өз ыңғайыңызға қарай қайталаңыз."],
      ["04 / Үй тапсырмасы", "Сабақ аралығында тапсырмаларды орындаңыз. Оқытушы жауаптарды тексеріп, пікірін береді."],
    ],
    readingLabel: "Кітапханада", readingTitle: "Оқыңыз. Байқаңыз. Есте сақтаңыз.", readingText: "Деңгейіңізге сай мәтіндерді таңдаңыз, бейтаныс сөзді басып, оны сөздігіңізге сақтаңыз. Ол сабақтан алынған сөздермен бірдей карточкаларға түседі.",
    readingSample: "Ағылшын тіліндегі шағын әңгіме", readingLine: "Every small step helps you grow.", readingHint: "Кабинетте сөзді басып, мағынасын біліңіз және сөздікке қосыңыз.",
    teacherEyebrow: "Құралдан бұрын адам", teacherTitle: "Сізбен бірге — шынайы оқытушы.", teacherText: "Жеке сабақтарды әртүрлі елдерден келген, оның ішінде ағылшын тілін ана тілі ретінде сөйлейтін оқытушылар өткізеді. Олар әңгімені мақсатыңызға бейімдейді, сабақтан кейін материалдарды тексереді және алға жылжуыңызға көмектеседі. Технология оларды алмастырмайды, тек көмектеседі.",
    processEyebrow: "Бастау оңай", processTitle: "Алғашқы кездесуден тұрақты сөйлеуге дейін", process: ["Аккаунт ашып, мақсатыңыз туралы айтып беріңіз.", "Өз уақыт белдеуіңіздегі ыңғайлы уақытты таңдаңыз.", "Сабақта сөйлесіп, кейін сөздерді, мәтіндерді және тапсырмаларды қайталаңыз."],
    pricesEyebrow: "Пакеттер", pricesTitle: "Анық шарттар, өз қарқыныңыз.", pricesText: "Әр пакеттің бағасы, сабақ саны, жарамдылық мерзімі және артықшылықтары академияның ағымдағы каталогынан алынады.", loading: "Пакеттер жүктелуде", empty: "Пакеттер әзірге көрсетілмейді. Бізге жазыңыз, сабақ таңдауға көмектесеміз.", choose: "Оқуды бастау", packName: "Бағдарлама", sale: "Жеңілдетілген баға", trialBody: (n: number) => `Егер академия ұсынысты қосқан болса, тіркеліп, сауалнаманы толтырғаннан кейін сізге ${n} сынақ сабағы қолжетімді болады.`,
    finalTitle: "Ағылшынша сенімдірек сөйлегіңіз келе ме?", finalText: "Тіркелуден бастаңыз. Деңгей, оқытушылар немесе кесте туралы сұрақ болса, бізге жазыңыз.",
    legal: "Құқықтық ақпарат", privacy: "Құпиялық саясаты", terms: "Оқу шарттары", back: "Жоғарыға", email: "Электрондық пошта",
  },
  en: {
    language: "Page language", home: "Omnica English home", signIn: "Sign in", register: "Start learning",
    eyebrow: "English that stays with you", heroA: "Speak in class.", heroB: "Remember afterwards.",
    hero: "One-to-one online lessons with teachers from different countries, including native English speakers. A live conversation becomes words, flashcards and practice for the time between lessons.",
    start: "Start learning", explore: "How it works", whatsapp: "Message Omnica English on WhatsApp",
    note: "One-to-one · 60 minutes · Google Meet", illustration: "Illustration of the learning process, not a platform screenshot",
    lesson: "In your lesson", live: "Live transcription for the teacher", review: "After the lesson", teacher: "Teacher reviews materials before publishing", word: "New words", wordExample: "Understand and use", card: "Review flashcard", cardFront: "to make progress", cardBack: "to advance towards a goal",
    pillarsEyebrow: "More than a conversation", pillarsTitle: "The lesson ends. Learning continues.", pillarsIntro: "You do not have to rely on memory alone: the materials you need to review live in your account.",
    features: [
      ["01 / Live lesson", "Your teacher leads a one-to-one lesson on Google Meet. Real-time transcription helps them work with the lesson material."],
      ["02 / Words into cards", "After the lesson, your teacher reviews AI-assisted notes and vocabulary. Published words become flashcards for review."],
      ["03 / Reading and practice", "Read library materials, save words to your list and review them with flashcards at your own pace."],
      ["04 / Homework", "Work on assignments between meetings. Your teacher reviews your answers and gives feedback."],
    ],
    readingLabel: "In the library", readingTitle: "Read. Notice. Remember.", readingText: "Choose texts for your level, tap an unfamiliar word and save it to your vocabulary. It joins the same flashcards as words from your lessons.",
    readingSample: "A short English story", readingLine: "Every small step helps you grow.", readingHint: "Tap a word in your account to find its meaning and add it to your list.",
    teacherEyebrow: "People before tools", teacherTitle: "A real teacher is with you.", teacherText: "One-to-one lessons are led by teachers from different countries, including native English speakers. They adapt the conversation to your goal, review materials after class and help you keep moving. Technology supports them; it does not replace them.",
    processEyebrow: "An easy start", processTitle: "From your first meeting to a speaking habit", process: ["Create an account and tell us about your goal.", "Choose a convenient time in your own time zone.", "Speak during the lesson; review words, reading and assignments afterwards."],
    pricesEyebrow: "Lesson packs", pricesTitle: "Clear terms, your pace.", pricesText: "Prices, lesson counts, validity and every included benefit come from the academy’s current catalogue.", loading: "Loading lesson packs", empty: "Packs are not showing right now. Message us and we will help you choose lessons.", choose: "Start learning", packName: "Programme", sale: "Sale price", trialBody: (n: number) => `After you register and complete onboarding, ${n === 1 ? "a trial lesson" : `${n} trial lessons`} will be available if the academy has enabled the offer.`,
    finalTitle: "Ready to speak with more confidence?", finalText: "Start with registration. Have a question about your level, teachers or schedule? Message us directly.",
    legal: "Legal information", privacy: "Privacy policy", terms: "Terms of learning", back: "Back to top", email: "Email",
  },
} satisfies Record<PublicLandingLocale, object>;
